/*
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sh.ory.hydra.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Extension Extension Extension Extension Extension Extension represents the ASN.1 structure of the same name. See RFC 5280, section 4.2.
 */
@ApiModel(description = "Extension Extension Extension Extension Extension Extension represents the ASN.1 structure of the same name. See RFC 5280, section 4.2.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-08T11:33:47.803525Z[GMT]")
public class Extension {
  public static final String SERIALIZED_NAME_CRITICAL = "Critical";
  @SerializedName(SERIALIZED_NAME_CRITICAL)
  private Boolean critical;

  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private List<Long> id = null;

  public static final String SERIALIZED_NAME_VALUE = "Value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private List<Integer> value = null;


  public Extension critical(Boolean critical) {
    
    this.critical = critical;
    return this;
  }

   /**
   * critical
   * @return critical
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "critical")

  public Boolean getCritical() {
    return critical;
  }


  public void setCritical(Boolean critical) {
    this.critical = critical;
  }


  public Extension id(List<Long> id) {
    
    this.id = id;
    return this;
  }

  public Extension addIdItem(Long idItem) {
    if (this.id == null) {
      this.id = new ArrayList<Long>();
    }
    this.id.add(idItem);
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Long> getId() {
    return id;
  }


  public void setId(List<Long> id) {
    this.id = id;
  }


  public Extension value(List<Integer> value) {
    
    this.value = value;
    return this;
  }

  public Extension addValueItem(Integer valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<Integer>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "value")

  public List<Integer> getValue() {
    return value;
  }


  public void setValue(List<Integer> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Extension extension = (Extension) o;
    return Objects.equals(this.critical, extension.critical) &&
        Objects.equals(this.id, extension.id) &&
        Objects.equals(this.value, extension.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(critical, id, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Extension {\n");
    sb.append("    critical: ").append(toIndentedString(critical)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

