/*
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sh.ory.hydra.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import sh.ory.hydra.model.Extension;
import sh.ory.hydra.model.IPNet;
import sh.ory.hydra.model.Name;
import sh.ory.hydra.model.URL;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Certificate
 */
public class CertificateTest {
    private final Certificate model = new Certificate();

    /**
     * Model tests for Certificate
     */
    @Test
    public void testCertificate() {
        // TODO: test Certificate
    }

    /**
     * Test the property 'authorityKeyId'
     */
    @Test
    public void authorityKeyIdTest() {
        // TODO: test authorityKeyId
    }

    /**
     * Test the property 'basicConstraintsValid'
     */
    @Test
    public void basicConstraintsValidTest() {
        // TODO: test basicConstraintsValid
    }

    /**
     * Test the property 'crLDistributionPoints'
     */
    @Test
    public void crLDistributionPointsTest() {
        // TODO: test crLDistributionPoints
    }

    /**
     * Test the property 'dnSNames'
     */
    @Test
    public void dnSNamesTest() {
        // TODO: test dnSNames
    }

    /**
     * Test the property 'emailAddresses'
     */
    @Test
    public void emailAddressesTest() {
        // TODO: test emailAddresses
    }

    /**
     * Test the property 'excludedDNSDomains'
     */
    @Test
    public void excludedDNSDomainsTest() {
        // TODO: test excludedDNSDomains
    }

    /**
     * Test the property 'excludedEmailAddresses'
     */
    @Test
    public void excludedEmailAddressesTest() {
        // TODO: test excludedEmailAddresses
    }

    /**
     * Test the property 'excludedIPRanges'
     */
    @Test
    public void excludedIPRangesTest() {
        // TODO: test excludedIPRanges
    }

    /**
     * Test the property 'excludedURIDomains'
     */
    @Test
    public void excludedURIDomainsTest() {
        // TODO: test excludedURIDomains
    }

    /**
     * Test the property 'extKeyUsage'
     */
    @Test
    public void extKeyUsageTest() {
        // TODO: test extKeyUsage
    }

    /**
     * Test the property 'extensions'
     */
    @Test
    public void extensionsTest() {
        // TODO: test extensions
    }

    /**
     * Test the property 'extraExtensions'
     */
    @Test
    public void extraExtensionsTest() {
        // TODO: test extraExtensions
    }

    /**
     * Test the property 'ipAddresses'
     */
    @Test
    public void ipAddressesTest() {
        // TODO: test ipAddresses
    }

    /**
     * Test the property 'isCA'
     */
    @Test
    public void isCATest() {
        // TODO: test isCA
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'issuingCertificateURL'
     */
    @Test
    public void issuingCertificateURLTest() {
        // TODO: test issuingCertificateURL
    }

    /**
     * Test the property 'keyUsage'
     */
    @Test
    public void keyUsageTest() {
        // TODO: test keyUsage
    }

    /**
     * Test the property 'maxPathLen'
     */
    @Test
    public void maxPathLenTest() {
        // TODO: test maxPathLen
    }

    /**
     * Test the property 'maxPathLenZero'
     */
    @Test
    public void maxPathLenZeroTest() {
        // TODO: test maxPathLenZero
    }

    /**
     * Test the property 'notBefore'
     */
    @Test
    public void notBeforeTest() {
        // TODO: test notBefore
    }

    /**
     * Test the property 'ocSPServer'
     */
    @Test
    public void ocSPServerTest() {
        // TODO: test ocSPServer
    }

    /**
     * Test the property 'permittedDNSDomains'
     */
    @Test
    public void permittedDNSDomainsTest() {
        // TODO: test permittedDNSDomains
    }

    /**
     * Test the property 'permittedDNSDomainsCritical'
     */
    @Test
    public void permittedDNSDomainsCriticalTest() {
        // TODO: test permittedDNSDomainsCritical
    }

    /**
     * Test the property 'permittedEmailAddresses'
     */
    @Test
    public void permittedEmailAddressesTest() {
        // TODO: test permittedEmailAddresses
    }

    /**
     * Test the property 'permittedIPRanges'
     */
    @Test
    public void permittedIPRangesTest() {
        // TODO: test permittedIPRanges
    }

    /**
     * Test the property 'permittedURIDomains'
     */
    @Test
    public void permittedURIDomainsTest() {
        // TODO: test permittedURIDomains
    }

    /**
     * Test the property 'policyIdentifiers'
     */
    @Test
    public void policyIdentifiersTest() {
        // TODO: test policyIdentifiers
    }

    /**
     * Test the property 'publicKey'
     */
    @Test
    public void publicKeyTest() {
        // TODO: test publicKey
    }

    /**
     * Test the property 'publicKeyAlgorithm'
     */
    @Test
    public void publicKeyAlgorithmTest() {
        // TODO: test publicKeyAlgorithm
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 'rawIssuer'
     */
    @Test
    public void rawIssuerTest() {
        // TODO: test rawIssuer
    }

    /**
     * Test the property 'rawSubject'
     */
    @Test
    public void rawSubjectTest() {
        // TODO: test rawSubject
    }

    /**
     * Test the property 'rawSubjectPublicKeyInfo'
     */
    @Test
    public void rawSubjectPublicKeyInfoTest() {
        // TODO: test rawSubjectPublicKeyInfo
    }

    /**
     * Test the property 'rawTBSCertificate'
     */
    @Test
    public void rawTBSCertificateTest() {
        // TODO: test rawTBSCertificate
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'signatureAlgorithm'
     */
    @Test
    public void signatureAlgorithmTest() {
        // TODO: test signatureAlgorithm
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'subjectKeyId'
     */
    @Test
    public void subjectKeyIdTest() {
        // TODO: test subjectKeyId
    }

    /**
     * Test the property 'urIs'
     */
    @Test
    public void urIsTest() {
        // TODO: test urIs
    }

    /**
     * Test the property 'unhandledCriticalExtensions'
     */
    @Test
    public void unhandledCriticalExtensionsTest() {
        // TODO: test unhandledCriticalExtensions
    }

    /**
     * Test the property 'unknownExtKeyUsage'
     */
    @Test
    public void unknownExtKeyUsageTest() {
        // TODO: test unknownExtKeyUsage
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
