/*
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sh.ory.hydra.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sh.ory.hydra.model.AttributeTypeAndValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Name
 */
public class NameTest {
    private final Name model = new Name();

    /**
     * Model tests for Name
     */
    @Test
    public void testName() {
        // TODO: test Name
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'extraNames'
     */
    @Test
    public void extraNamesTest() {
        // TODO: test extraNames
    }

    /**
     * Test the property 'locality'
     */
    @Test
    public void localityTest() {
        // TODO: test locality
    }

    /**
     * Test the property 'names'
     */
    @Test
    public void namesTest() {
        // TODO: test names
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'streetAddress'
     */
    @Test
    public void streetAddressTest() {
        // TODO: test streetAddress
    }

}
