/*
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sh.ory.hydra.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for URL
 */
public class URLTest {
    private final URL model = new URL();

    /**
     * Model tests for URL
     */
    @Test
    public void testURL() {
        // TODO: test URL
    }

    /**
     * Test the property 'forceQuery'
     */
    @Test
    public void forceQueryTest() {
        // TODO: test forceQuery
    }

    /**
     * Test the property 'fragment'
     */
    @Test
    public void fragmentTest() {
        // TODO: test fragment
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'opaque'
     */
    @Test
    public void opaqueTest() {
        // TODO: test opaque
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'rawPath'
     */
    @Test
    public void rawPathTest() {
        // TODO: test rawPath
    }

    /**
     * Test the property 'rawQuery'
     */
    @Test
    public void rawQueryTest() {
        // TODO: test rawQuery
    }

    /**
     * Test the property 'scheme'
     */
    @Test
    public void schemeTest() {
        // TODO: test scheme
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
